baseURL = 'https://carlose-cortesg.github.io/'
languageCode = 'en-us'
title = 'Carlos Eduardo Cortés Gómez'
theme = 'PaperMod'
enableEmoji = true

[params]
  description = "Data Scientist/Engineer based in Colombia 🇨🇴"
  author = "Carlos Eduardo Cortés Gómez"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[params.profileMode]
  enabled = true
  title = "Carlos Eduardo Cortés Gómez 🇨🇴"
  subtitle = "Data Scientist/Engineer 📊 | Bird Watcher 🦜"
  imageUrl = "/profile.PNG"
  imageTitle = "my profile"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/carlosecortesg"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/carlose-cortesg"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "skills"
    name = "Skills"
    url = "/skills/"
    weight = 20 